[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qrulnacf6l6lt2vlpc8y2yudlgzs9hzrfa9p66fv4p7vk8utf6m4554t3ak"]

[[validator_account]]
address = "tnam1q9q3lph40w88cs5000k48thkw3f7s0m6mqrtfgss"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "127.0.0.1:27656"

[validator_account.consensus_key]
pk = "tpknam1qr9u5py97pdmcvnrxhzuuv79ydv5rw7r9z402sucwt6h0lvmmmwqy2wrweg"
authorization = "signam1qqc8l8rvl5kx36sgnrqfzsyc5p6047c3xp5hqnhz8w7qmqzw5umqtglaejn6ekajm2jt98qhwlje38wdackknk4qrj9jycutmw2eevgvlv0uq6"

[validator_account.protocol_key]
pk = "tpknam1qrenhfdphzpszlr7fzand6qgmppge430g3a2lquqzhz64fkve5mq2hdfjaa"
authorization = "signam1qrgem8wds2eupup8a5wl8he9ftvx6a4elyt97322q483vh8j3fm0x330h0pfcpumpm2tqgz2chmw567mhxtqdlncggz8uc8u66svnsqw26ra2v"

[validator_account.tendermint_node_key]
pk = "tpknam1qpgcgptcjl22hl2te2uqnp33aqjmvfaud3a3f3sgtxezg7uu5rsv6d2flr3"
authorization = "signam1qq05nmg0v5w9377235dpuk7k5k7kkjx5zyewqr4ecd0yyawz3ll2r7jxq9ss9wpnl69c9s0t9aqyuf7y6e7avh8m6d6nvyt5qnmaz5qyay596t"

[validator_account.eth_hot_key]
pk = "tpknam1qypnh98mexms8edj8rcwu0cayx0459p39dwzsffxrr394mf4cse707qcctyrx"
authorization = "signam1q86yxmjctxx7h59cl3tz8sf6j9r6wlxplv282fkm8yxyc8wvjkz4q8lhcavq8xa9jk3clnuxfpdg9hnp4t589ld3v2lv9tla3phucle7qysufnv4"

[validator_account.eth_cold_key]
pk = "tpknam1qypz8zr0w8lsz3s98vh4p974xuxeedpecj9s2l3326r3kdz4tc0snrcpnc8yv"
authorization = "signam1qxxc4ulf7qlc0vdz477sgg3hms07vn3apkluxrq0erhchtw90yw9z2m6kmjcrgc8zks0fvwsmr88q0dxd3cs9zy7pz94wuum5urwu868qyzvqmr5"

[validator_account.metadata]
email = "null@null.net"

[validator_account.signatures]
tpknam1qrulnacf6l6lt2vlpc8y2yudlgzs9hzrfa9p66fv4p7vk8utf6m4554t3ak = "signam1qzg4cjyctnrnl8vpgp95tvjgwpcye3xfwchxq66de6wqn5ujwk6m69qd4n4mzx40ch48xtzhdhnq9m605pwm2v0gy422ehula4xt89cz39ngg0"

[[bond]]
source = "tnam1q9q3lph40w88cs5000k48thkw3f7s0m6mqrtfgss"
validator = "tnam1q9q3lph40w88cs5000k48thkw3f7s0m6mqrtfgss"
amount = "100000"

[bond.signatures]
tpknam1qrulnacf6l6lt2vlpc8y2yudlgzs9hzrfa9p66fv4p7vk8utf6m4554t3ak = "signam1qzwn66j9dx49eyg72fd7s2cw5l2va3p9dj07te0egf93p6qatf95hk447ty6s6cds55ggtz8dcr65xqqz00a0wclqrhqcknk504a2ps9jqe6f7"
